#!/usr/bin/env python3
"""Build GitHub Pages-friendly HTML from Markdown landing pages.

cheatSheet/.nojekyll serves .md as raw text on Pages — these HTML editions render
in the browser. Regenerated by build_github_view.py and the Pages workflow.
"""

from __future__ import annotations

import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHEAT = ROOT / "cheatSheet"

PAGE_CSS = """
:root{--bg:#f5f5f4;--card:#fff;--text:#1a1a1a;--muted:#666;--accent:#185fa5;--border:rgba(0,0,0,.12);--r:12px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
@media(prefers-color-scheme:dark){:root{--bg:#0d1117;--card:#161b22;--text:#e6edf3;--muted:#8b949e;--border:rgba(255,255,255,.12);--accent:#58a6ff}}
*{box-sizing:border-box;margin:0;padding:0}
body{min-height:100vh;background:var(--bg);color:var(--text);padding:40px 20px;line-height:1.65}
.wrap{max-width:760px;margin:0 auto}
.back{font-size:.9rem;margin-bottom:20px}
.back a{color:var(--accent);text-decoration:none}
.back a:hover{text-decoration:underline}
article{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:24px}
article h1{font-size:1.45rem;margin-bottom:12px}
article h2{font-size:1.15rem;margin:1.6rem 0 .6rem;padding-bottom:4px;border-bottom:1px solid var(--border)}
article h3{font-size:1rem;margin:1.2rem 0 .4rem}
article p,article li{font-size:.95rem;margin:.5rem 0}
article ul,article ol{padding-left:1.4rem}
article a{color:var(--accent)}
article code{background:rgba(127,127,127,.12);padding:1px 5px;border-radius:4px;font-size:.88em}
article pre{background:rgba(127,127,127,.1);padding:12px;border-radius:8px;overflow-x:auto;font-size:.85rem;margin:10px 0}
article table{width:100%;border-collapse:collapse;font-size:.9rem;margin:12px 0}
article th,article td{border:1px solid var(--border);padding:8px 10px;text-align:left;vertical-align:top}
article th{background:rgba(127,127,127,.08)}
.note{background:rgba(24,95,165,.08);border:1px solid var(--border);border-radius:8px;padding:12px 14px;margin:12px 0;font-size:.9rem}
.toc a{display:block;padding:3px 0;text-decoration:none}
.toc a:hover{text-decoration:underline}
.badge{display:inline-block;font-size:.72rem;padding:2px 8px;border-radius:100px;margin-left:6px}
.be{background:#eaf3de;color:#27500a}.bm{background:#faeeda;color:#633806}.bh{background:#fcebeb;color:#791f1f}
"""

DIFF_LABEL = {"e": "Easy", "m": "Medium", "h": "Hard"}
DIFF_BADGE = {"e": "be", "m": "bm", "h": "bh"}


def page_shell(title: str, body: str, back_href: str = "index.html") -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)}</title>
<style>{PAGE_CSS}</style>
</head>
<body>
<div class="wrap">
  <p class="back"><a href="{html.escape(back_href)}">← Cheat sheet index</a></p>
  <article>{body}</article>
</div>
</body>
</html>"""


def inline_md(text: str) -> str:
    text = html.escape(text, quote=False)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(
        r"\[([^\]]+)\]\(([^)]+)\)",
        lambda m: f'<a href="{html.escape(m.group(2), quote=True)}">{m.group(1)}</a>',
        text,
    )
    return text


def md_to_html(md: str) -> str:
    """Minimal Markdown → HTML for landing/docs pages."""
    lines = md.splitlines()
    out: list[str] = []
    i = 0
    in_code = False
    code_buf: list[str] = []
    list_type: str | None = None

    def close_list():
        nonlocal list_type
        if list_type:
            out.append(f"</{list_type}>")
            list_type = None

    while i < len(lines):
        line = lines[i]

        if line.startswith("```"):
            close_list()
            if in_code:
                out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
                code_buf = []
                in_code = False
            else:
                in_code = True
            i += 1
            continue

        if in_code:
            code_buf.append(line)
            i += 1
            continue

        if line.startswith("|") and "|" in line[1:]:
            close_list()
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                row = [c.strip() for c in lines[i].strip("|").split("|")]
                if not all(re.match(r"^[-:]+$", c) for c in row):
                    rows.append(row)
                i += 1
            if rows:
                out.append("<table><thead><tr>")
                for cell in rows[0]:
                    out.append(f"<th>{inline_md(cell)}</th>")
                out.append("</tr></thead><tbody>")
                for row in rows[1:]:
                    out.append("<tr>")
                    for cell in row:
                        out.append(f"<td>{inline_md(cell)}</td>")
                    out.append("</tr>")
                out.append("</tbody></table>")
            continue

        if line.startswith("### "):
            close_list()
            out.append(f"<h3>{inline_md(line[4:])}</h3>")
        elif line.startswith("## "):
            close_list()
            out.append(f"<h2>{inline_md(line[3:])}</h2>")
        elif line.startswith("# "):
            close_list()
            out.append(f"<h1>{inline_md(line[2:])}</h1>")
        elif re.match(r"^[-*] ", line):
            if list_type != "ul":
                close_list()
                out.append("<ul>")
                list_type = "ul"
            out.append(f"<li>{inline_md(line[2:])}</li>")
        elif re.match(r"^\d+\. ", line):
            if list_type != "ol":
                close_list()
                out.append("<ol>")
                list_type = "ol"
            item = re.sub(r"^\d+\. ", "", line)
            out.append(f"<li>{inline_md(item)}</li>")
        elif line.strip() == "---":
            close_list()
            out.append("<hr>")
        elif line.strip() == "":
            close_list()
        else:
            close_list()
            out.append(f"<p>{inline_md(line)}</p>")
        i += 1

    close_list()
    if in_code and code_buf:
        out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
    return "\n".join(out)


def rewrite_pages_links(md: str, base_dir: Path) -> str:
    """Point Markdown links at HTML equivalents for GitHub Pages."""
    rewrites = {
        "github/v15/index.md": "github/v15/index.html",
        "github/v10-cards/index.md": "github/v10-cards/index.html",
        "github/README.md": "github/index.html",
        "VIEW_ON_GITHUB.md": "VIEW_ON_GITHUB.html",
        "interview-quick-fire.md": "interview-quick-fire.html",
        "system_design_cheatsheet_v14.html": "system_design_cheatsheet_v14.html",
        "system_design_cheatsheet_v15_github.html": "system_design_cheatsheet_v15_github.html",
        "SystemDesign_Complete_v10.html": "SystemDesign_Complete_v10.html",
        "SystemDesign_Complete_v10_github.html": "SystemDesign_Complete_v10_github.html",
        "github/v15-static.html": "github/v15-static.html",
        "EDA_Interview_Question_Bank_Complete.html": "EDA_Interview_Question_Bank_Complete.html",
        "CHANGELOG.md": "CHANGELOG.html",
    }

    def repl(m: re.Match) -> str:
        text, url = m.group(1), m.group(2)
        for old, new in rewrites.items():
            if url == old or url.endswith("/" + old):
                url = new if not url.startswith("../") else url
        if url.endswith(".md"):
            # Relative .md in github/ → pre-rendered HTML index anchors not available; keep note in index pages
            if base_dir.name == "cheatSheet" and "github/" in url:
                pass
        return f"[{text}]({url})"

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, md)


def write_md_as_html(md_path: Path, html_path: Path, back_href: str) -> None:
    md = md_path.read_text(encoding="utf-8")
    md = rewrite_pages_links(md, md_path.parent)
    body = md_to_html(md)
    title_m = re.search(r"^# (.+)$", md, re.M)
    title = title_m.group(1) if title_m else html_path.stem
    html_path.write_text(page_shell(title, body, back_href), encoding="utf-8")


def write_v15_index_html(systems: list[dict]) -> None:
    framework = """<h2>Delivery framework</h2>
<ol>
<li><strong>Requirements</strong> (3–5 min) — functional + NFRs, draw out-of-scope line</li>
<li><strong>Estimation</strong> — QPS, storage, bandwidth to justify decisions</li>
<li><strong>API design</strong> — REST / WebSocket / gRPC, name routes explicitly</li>
<li><strong>Data model</strong> — entities, SQL vs NoSQL with justification</li>
<li><strong>High-level design</strong> — client → LB → services → DB/cache</li>
<li><strong>Deep dives</strong> — 2–3 hardest problems, tradeoffs, failure modes</li>
</ol>
<p><strong>Key numbers:</strong> Redis ~100K–1M ops/s · Single DB ~10K–50K QPS · Kafka ~1M+ msgs/s · Cross-region ~100–200ms</p>"""

    links = """<div class="note">
<b>GitHub Pages:</b> Per-system <code>.md</code> files show as raw text here.
Use the HTML editions below — all 40 cards, search, and tabs on Pages.
</div>
<p>
<a href="../../system_design_cheatsheet_v15_github.html">v15 pre-rendered HTML (recommended on Pages)</a> ·
<a href="../../system_design_cheatsheet_v14.html">Full interactive v15</a> ·
<a href="../v15-static.html">Static HTML (no JS)</a>
</p>"""

    toc = ['<div class="toc">']
    for diff_key, label in [("e", "Easy"), ("m", "Medium"), ("h", "Hard")]:
        group = [s for s in systems if s["diff"] == diff_key]
        if not group:
            continue
        toc.append(f"<h3>{label} ({len(group)})</h3>")
        for s in group:
            badge = DIFF_BADGE[s["diff"]]
            href = f"../../system_design_cheatsheet_v15_github.html#{s['slug']}"
            toc.append(
                f'<a href="{href}">{html.escape(s["title"])}'
                f' <span class="badge {badge}">{DIFF_LABEL[s["diff"]]}</span></a>'
            )
    toc.append("</div>")

    body = (
        "<h1>Staff+ Interview Prep (v15)</h1>"
        "<p>40 system design cards for Staff+ interview prep.</p>"
        + links
        + framework
        + "".join(toc)
    )
    out = CHEAT / "github" / "v15" / "index.html"
    out.write_text(page_shell("Staff+ Interview Prep (v15)", body, "../../index.html"), encoding="utf-8")


def write_v10_index_html(systems: list[dict]) -> None:
    links = """<div class="note">
<b>GitHub Pages:</b> Per-system <code>.md</code> files show as raw text here.
Open the pre-rendered HTML edition for all 26 ByteByteGo cards.
</div>
<p>
<a href="../../SystemDesign_Complete_v10_github.html">v10 pre-rendered HTML (recommended on Pages)</a> ·
<a href="../../SystemDesign_Complete_v10.html">Full interactive v10</a>
</p>"""

    toc = ['<div class="toc">']
    for diff_key, label in [("e", "Easy"), ("m", "Medium"), ("h", "Hard")]:
        group = [s for s in systems if s["diff"] == diff_key]
        if not group:
            continue
        toc.append(f"<h3>{label} ({len(group)})</h3>")
        for s in group:
            badge = DIFF_BADGE[s["diff"]]
            href = f"../../SystemDesign_Complete_v10_github.html#card-{s['id']}"
            toc.append(
                f'<a href="{href}">{html.escape(s["title"])}'
                f' <span class="badge {badge}">{DIFF_LABEL[s["diff"]]}</span></a>'
            )
    toc.append("</div>")

    body = (
        "<h1>System Cards (v10)</h1>"
        "<p>26 ByteByteGo system cards — summaries and interview scripts.</p>"
        + links
        + "".join(toc)
    )
    out = CHEAT / "github" / "v10-cards" / "index.html"
    out.write_text(page_shell("System Cards (v10)", body, "../../index.html"), encoding="utf-8")


def write_github_hub_html() -> None:
    body = """<h1>GitHub-viewable cheat sheets</h1>
<p>Markdown per-system files render in the <strong>GitHub repo browser</strong>.
On <strong>GitHub Pages</strong>, use the HTML editions linked below.</p>
<table>
<thead><tr><th>View</th><th>Best for</th></tr></thead>
<tbody>
<tr><td><a href="v15/index.html">v15 index (Pages HTML)</a></td><td>40 systems — links to pre-rendered cards</td></tr>
<tr><td><a href="v15-static.html">v15 static HTML</a></td><td>Same content, expandable sections, no JS</td></tr>
<tr><td><a href="v10-cards/index.html">v10 cards index (Pages HTML)</a></td><td>26 ByteByteGo cards</td></tr>
<tr><td><a href="v10-reference-index.md">v10 reference index</a></td><td>ByteByteGo chapters (Markdown)</td></tr>
</tbody>
</table>
<h2>Interactive versions (full features)</h2>
<ul>
<li><a href="../system_design_cheatsheet_v14.html">system_design_cheatsheet_v14.html</a> — v15, search, interview mode</li>
<li><a href="../system_design_cheatsheet_v15_github.html">system_design_cheatsheet_v15_github.html</a> — v15 pre-rendered for Pages</li>
<li><a href="../SystemDesign_Complete_v10.html">SystemDesign_Complete_v10.html</a> — ByteByteGo reference + cloud CLI</li>
<li><a href="../SystemDesign_Complete_v10_github.html">SystemDesign_Complete_v10_github.html</a> — v10 pre-rendered for Pages</li>
<li><a href="../EDA_Interview_Question_Bank_Complete.html">EDA_Interview_Question_Bank_Complete.html</a> — EDA interview bank</li>
</ul>"""
    (CHEAT / "github" / "index.html").write_text(
        page_shell("GitHub-viewable cheat sheets", body, "../index.html"),
        encoding="utf-8",
    )


def main(v15_systems: list[dict] | None = None, v10_systems: list[dict] | None = None) -> None:
    write_md_as_html(CHEAT / "VIEW_ON_GITHUB.md", CHEAT / "VIEW_ON_GITHUB.html", "index.html")
    (CHEAT / "CHANGELOG.html").write_text(
        page_shell(
            "Changelog",
            md_to_html((ROOT / "CHANGELOG.md").read_text(encoding="utf-8")),
            "index.html",
        ),
        encoding="utf-8",
    )
    write_github_hub_html()
    if v15_systems:
        write_v15_index_html(v15_systems)
    if v10_systems:
        write_v10_index_html(v10_systems)
    print("Wrote GitHub Pages landing HTML (VIEW_ON_GITHUB, CHANGELOG, github/index, v15/index, v10/index)")


if __name__ == "__main__":
    main()
